
modLoader="javafml"
loaderVersion="[43,)"
license="MIT"


[[mods]]
modId="crowns"
version="2.0.30"
displayName="Creating Rotation Operated With Nuclear Science"
logoFile="logo.png"
credits='''

'''
authors="Real Ant Engineer"

description='''
'''

[[dependencies.crowns]]
modId="create"
mandatory=true
versionRange="[0.6.0.2,)"
ordering="NONE"
side="BOTH"

[[dependencies.crowns]]
modId="formicapi"
mandatory=true
versionRange="[1.6.6,)"
ordering="NONE"
side="BOTH"