
modLoader="javafml"
loaderVersion="[1,)"
license="MIT"


[[mods]]
modId="crowns"
version="2.1.6"
displayName="Creating Rotation Operated With Nuclear Science"
logoFile= "logo.png"
credits='''

'''
authors="Real Ant Engineer"

description='''
'''

[[dependencies.crowns]]
modId="create"
mandatory=true
versionRange="[6.0.4,)"
ordering="NONE"
side="BOTH"

[[dependencies.crowns]]
modId="formicapi"
mandatory=true
versionRange="[2.2.3,)"
ordering="NONE"
side="BOTH"

[[mixins]]
config = "crowns.mixins.json"


